# Generated by Django 4.1.4 on 2023-06-03 22:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('floor_number', models.IntegerField()),
                ('room_number', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='meeting',
            name='duration',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='meeting',
            name='start_time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AddField(
            model_name='meeting',
            name='room',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='meetings.room'),
        ),
    ]
